Controllers/NotesController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Storage;
using Noting.Data;
using Noting.Models;
using Noting.Models.Builders;
using Noting.Services;

namespace Noting.Controllers
{
    public class NotesController : Controller
    {
        private readonly MvcNoteContext _context;
        private readonly INoteService<Note> _noteService;

        public NotesController(MvcNoteContext context, INoteService<Note> noteService)
        {
            _context = context;
            _noteService = noteService;
        }

        // GET: Notes
        public async Task<IActionResult> Index()
        {
            return View(await _noteService.GetAll());
        }

        // GET: Notes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var note = await _noteService.GetDetails(id);

            if (note == null) return NotFound();
            return View(note);
        }

        // GET: Notes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Keywords, Note")] NotePageViewModel model)
        {
            model.Note.CreatedAt = DateTime.Now;
            model.Note.LastModified = DateTime.Now;

            if (ModelState.IsValid)
            {
                if (await _noteService.CreateNote(model))
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        } 

        // GET: Notes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            var note = await _noteService.GetDetails(id);
            if (note == null) return NotFound();

            var model = new NotePageViewModel
            {
                Note = note,
                Keywords = note.Keywords.Any() ?
                            (from kw in note.Keywords select kw.Name).ToList()
                            :
                            new List<string>()
            };

            return View(model);
        }

        // POST: Notes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Keywords, Note")] NotePageViewModel model)
        {
            if (id != model.Note.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var noteEditSuccess = await _noteService.EditNote(id, model);
                if (noteEditSuccess == true)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model.Note);
        }

        // GET: Notes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var note = await _context.Note
                .FirstOrDefaultAsync(m => m.Id == id);
            if (note == null)
            {
                return NotFound();
            }

            return View(note);
        }

        // POST: Notes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var note = await _context.Note.FindAsync(id);
            _context.Note.Remove(note);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NoteExists(string id)
        {
            return _context.Note.Any(e => e.Id == id);
        }

        async private Task<ICollection<NoteRelation>> GetLinkedNoteRelations(string id)
        {
            try
            {
                var relations = from noteRel in _context.NoteRelation
                                where noteRel.ParentId == id
                                join n in _context.Note on noteRel.ChildId equals n.Id
                                select new NoteRelation { Child = n, ChildId = noteRel.ChildId, ParentId = noteRel.ParentId, Id = noteRel.Id };

                return await relations.ToListAsync();
            }
            catch (Exception e)
            {
                return null;
            }
        }

        async private Task<ICollection<SpacedRepetitionAttempt>> GetAttemptsByHistoryId(string id)
        {
            List<SpacedRepetitionAttempt> attempts = null;
            try
            {
                if (await _context.SpacedRepetitionAttempts.AnyAsync() && id != null)
                {
                    attempts = await (from a in _context.SpacedRepetitionAttempts
                                      where a.SpacedRepetitionHistoryId == id
                                      select a).ToListAsync();
                }
            }
            catch (Exception e) { }
            return attempts;
        }

        async private Task<SpacedRepetitionHistory> GetHistoryByNoteId(string id)
        {
            List<SpacedRepetitionHistory> histories = null;
            SpacedRepetitionHistory history = null;
            try
            {
                if (await _context.SpacedRepetitionHistories.AnyAsync())
                {
                    histories = await (from h in _context.SpacedRepetitionHistories
                                       where h.NoteId == id
                                       select h).ToListAsync();
                }
                history = histories.ElementAtOrDefault(0);
            }
            catch (Exception e) { }
            return history;
        }

        async private Task<ICollection<Keyword>> GetKeywordsByNoteId(string id)
        {
            try
            {
                // Set keywords if any
                var keywords = await (from keyword in _context.Keyword
                                      where keyword.NoteId == id
                                      select keyword).ToListAsync();
                return keywords;
            }
            catch (Exception e)
            {
                return null;
            }
        }

        async private void AddKeywordsToDbModel(Note note, ICollection<string> keywords)
        {
            using IDbContextTransaction dbContextTransaction = await _context.Database.BeginTransactionAsync();
            foreach (var k in keywords)
            {
                _context.Keyword.Add(
                    new Keyword
                    {
                        Name = k,
                        NoteId = note.Id
                    }
                );
            }
            await _context.SaveChangesAsync();
            await dbContextTransaction.CommitAsync();
        }

        async private Task<Note> AddNoteToDb(Note model)
        {
            using IDbContextTransaction dbContextTransaction = await _context.Database.BeginTransactionAsync();
            var savedNoteEntry = _context.Note.Add(model);
            await _context.SaveChangesAsync();
            await dbContextTransaction.CommitAsync();

            return model;
        }
    }
}

Controllers/SpacedRepetitionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Noting.Data;
using Noting.Models;
using Noting.Models.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Noting.Controllers
{
    public class SpacedRepetitionController : Controller
    {
        private readonly MvcNoteContext _context;

        public SpacedRepetitionController(MvcNoteContext context)
        {
            _context = context;
        }

        // GET: SpacedRepetition
        public async Task<IActionResult> Index()
        {
            // Setup five levels of note box
            ICollection<NoteBox> noteBoxes = SetupBoxes(5);

            if (!(_context.NoteBoxRelations.Any())) return View(noteBoxes);

            // Add relations to the NoteBox collection
            await AddRelationsToNoteBoxes(noteBoxes);

            return View(noteBoxes);
        }

        // GET: Attempt/:id
        public async Task<IActionResult> Attempt(string id)
        {
            if (id == null) return NotFound();
            var attempt = await _context.SpacedRepetitionAttempts.FirstOrDefaultAsync(m => m.Id == id);
            if (attempt == null) return NotFound();

            try
            {
                attempt.SpacedRepetitionHistory =
                    await _context.SpacedRepetitionHistories.FirstOrDefaultAsync(m => m.Id == attempt.SpacedRepetitionHistoryId);
            }
            catch (Exception e)
            {
            
            }

            return View(attempt);
        }

        // GET: Start/:level
        public async Task<IActionResult> Start(string level)
        {
            level = level.ToUpper();
            // Validity checks
            if (!Enum.IsDefined(typeof(Level), level)) return NotFound();
            if (!_context.NoteBoxRelations.Any()) return NotFound();

            // Get all NoteBoxRelation's where the Level matches the passed in Level
            var noteBoxRelations = await (from noteBoxRelation in _context.NoteBoxRelations
                                          where noteBoxRelation.Level == (Level) Enum.Parse(typeof(Level), level)
                                          select noteBoxRelation).ToListAsync();
            NoteBox notesBox = new NoteBox 
            { 
                Level = (Level) Enum.Parse(typeof(Level), level),
                Notes = new List<NoteBoxRelation>()
            };

            foreach (var rel in noteBoxRelations)
            {
                // Get the note
                rel.Note = await _context.Note.FirstOrDefaultAsync(m => m.Id == rel.NoteId);
                
                // Add the notes history
                rel.Note.SpacedRepetitionHistory = await GetHistoryByNoteId(rel.NoteId);
                rel.Note.SpacedRepetitionHistory.SpacedRepetitionAttempts =
                    await GetAttemptsByHistoryId(rel.Note.SpacedRepetitionHistory.Id);
                
                // Add the NoteBoxRelation to the notesBox
                notesBox.Notes.Add(rel);
            }
            return View(notesBox);
        }

        // POST: Attempt
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Attempt([Bind("Correct", "SpacedRepetitionHistoryId")] SpacedRepetitionAttempt attempt)
        {
            attempt.AttemptDate = DateTime.Now;

            if (ModelState.IsValid)
            {
                if (attempt.SpacedRepetitionHistoryId == null) return RedirectToAction(nameof(Index));
                var history = await _context.SpacedRepetitionHistories
                                            .FirstOrDefaultAsync(m => m.Id == attempt.SpacedRepetitionHistoryId);
                if (history == null) return RedirectToAction(nameof(Index));

                _context.SpacedRepetitionAttempts.Add(attempt);
                await _context.SaveChangesAsync();

                return RedirectToAction("History", new { id = history.Id });
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: History/:id
        public async Task<IActionResult> History(string id)
        {
            if (id == null) return NotFound();
            var history = await _context.SpacedRepetitionHistories.FirstOrDefaultAsync(m => m.Id == id);
            if (history == null) return NotFound();

            try
            {
                history.Note = await _context.Note.FirstOrDefaultAsync(m => m.Id == history.NoteId);
                history.SpacedRepetitionAttempts = await _context.SpacedRepetitionAttempts
                                                                 .Where(m => m.SpacedRepetitionHistoryId == history.Id)
                                                                 .ToListAsync();
            }
            catch (Exception e)
            {

            }

            return View(history);
        }

        async private Task AddRelationsToNoteBoxes(ICollection<NoteBox> noteBoxes)
        {
            try
            {
                // Get all NoteBoxRelation objects in DB
                var noteBoxRelations = await (from rel in _context.NoteBoxRelations
                                              select rel).ToListAsync();

                // for each NoteBoxRelation
                for (int i = 0; i < noteBoxRelations.Count; i++)
                {
                    // Get the note for the current NoteBoxRelation
                    INoteBuilder<Note> noteBuilder = (await _context.Note.FirstOrDefaultAsync(n => n.Id == noteBoxRelations[i].NoteId)).Builder();

                    // Get the history and add to the builder
                    var h = await GetHistoryByNoteId(noteBoxRelations[i].NoteId);
                    h.SpacedRepetitionAttempts = await GetAttemptsByHistoryId(h.Id);
                    noteBuilder.WithSpacedRepetitionHistory(h);

                    // Set the Note property on the NoteBoxRelation
                    noteBoxRelations[i].Note = noteBuilder.BuildNote();

                    // for each NoteBox
                    for (int j = 0; j < noteBoxes.Count; j++)
                    {
                        // Add relation to NoteBox
                        TryAddRelationToNoteBox(noteBoxes.ElementAt(j), noteBoxRelations[i]);

                    }
                }
            }
            catch (Exception e)
            {
                noteBoxes = SetupBoxes(5);
            }
        }

        private void TryAddRelationToNoteBox(NoteBox noteBox, NoteBoxRelation noteBoxRelation)
        {
            // if the NoteBox Level matches the NoteBoxRelations Level
            if (noteBox.Level == noteBoxRelation.Level)
            {
                // add the NoteBoxRelation to the NoteBox
                noteBox.Notes
                       .Add(noteBoxRelation);
            }
        }

        private ICollection<NoteBox> SetupBoxes(int v)
        {
            var noteBoxes = new List<NoteBox>();
            for (int i = 0; i < v; i++)
            {
                noteBoxes.Add(new NoteBox { Level = (Level)i, Notes = new List<NoteBoxRelation>() });
            }
            return noteBoxes;
        }

        private protected void AddRepetitionAttempt(string noteId, SpacedRepetitionAttempt spacedRepetitionAttempt)
        {
            //_context
        }

        async private protected void UpgradeNote(string noteId)
        {
            // Update the Level of the Note
            ICollection<NoteBoxRelation> oldRelation = (from rel in _context.NoteBoxRelations
                                                        where rel.NoteId == noteId
                                                        select rel).ToList();
            var oldRel = oldRelation.SingleOrDefault();

            if (oldRel.Level < Level.FIVE)
            {
                oldRel.Level += 1;
            }
            // Remove from this box by updating
            try
            {
                _context.NoteBoxRelations.Update(oldRel);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {

            }
        }

        async private protected void DowngradeNote(string noteId)
        {
            // Downgrade the Level of the Note to Level One
            // Update the Level of the Note
            ICollection<NoteBoxRelation> oldRelation = (from rel in _context.NoteBoxRelations
                                                        where rel.NoteId == noteId
                                                        select rel).ToList();
            var oldRel = oldRelation.SingleOrDefault();

            if (oldRel.Level == Level.ONE) return;

            oldRel.Level = Level.ONE;

            // Remove from this box by updating
            try
            {
                _context.NoteBoxRelations.Update(oldRel);
                await _context.SaveChangesAsync();
            }
            catch (Exception e)
            {

            }
        }

        async private Task<ICollection<SpacedRepetitionAttempt>> GetAttemptsByHistoryId(string id)
        {
            List<SpacedRepetitionAttempt> attempts = null;
            try
            {
                if (await _context.SpacedRepetitionAttempts.AnyAsync() && id != null)
                {
                    attempts = await (from a in _context.SpacedRepetitionAttempts
                                      where a.SpacedRepetitionHistoryId == id
                                      select a).ToListAsync();
                }
            }
            catch (Exception e) { }
            return attempts;
        }

        async private Task<SpacedRepetitionHistory> GetHistoryByNoteId(string id)
        {
            List<SpacedRepetitionHistory> histories = null;
            SpacedRepetitionHistory history = null;
            try
            {
                if (await _context.SpacedRepetitionHistories.AnyAsync())
                {

Views/SpacedRepetition/Attempt.cshtml
@model Noting.Models.SpacedRepetitionAttempt

@{
    ViewData["Title"] = "Attempt";
}

<h1>Attempt</h1>

<div>
    <h4>SpacedRepetitionAttempt</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SpacedRepetitionHistory.Question)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SpacedRepetitionHistory.Question)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AttemptDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AttemptDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Correct)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Correct)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="History" asp-route-id="@Model.SpacedRepetitionHistoryId">Full history</a>
    <a asp-action="Index">Back to List</a>
</div>

Views/SpacedRepetition/History.cshtml
@model Noting.Models.SpacedRepetitionHistory

@{
    ViewData["Title"] = "History";
}

<h1>History</h1>

<div>
    <h4>Spaced Repetition History</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Note.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Note.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NextScheduledAttempt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NextScheduledAttempt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>

    <h4>Attempts</h4>
    @foreach (var attempt in Model.SpacedRepetitionAttempts)
    {
        <dl>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => attempt.AttemptDate)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => attempt.AttemptDate)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => attempt.Correct)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => attempt.Correct)
            </dd>
        </dl>
        <a asp-action="Attempt" asp-route-id="@attempt.Id">Edit</a>
        <hr />
    }
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/SpacedRepetition/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Noting.Models.NoteBox>
@{
    ViewData["Title"] = "Index";
}

<h1>Spaced Repetition</h1>
<p class="lead">Repeating for the future</p>

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Note Title</th>
                <th>Box</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var box in Model)
            {
                @foreach (var note in box.Notes)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(model => note.Note.Title)
                        </td>
                        <td>
                            @Html.DisplayFor(model => note.Level)
                        </td>
                        <td>
                            @if (note.Note.SpacedRepetitionHistory != null)
                            {
                                <a asp-controller="SpacedRepetition" asp-action="History" asp-route-id="@note.Note.SpacedRepetitionHistory.Id">
                                    History
                                </a>
                            }
                            <a asp-controller="Notes" asp-action="Edit" asp-route-id="@note.Note.Id">Edit</a> |
                            <a asp-controller="Notes" asp-action="Details" asp-route-id="@note.Note.Id">Details</a> |
                            <a asp-controller="Notes" asp-action="Delete" asp-route-id="@note.Note.Id">Delete</a>
                        </td>
                    </tr>
                }

            }
        </tbody>
        </table>
    </div>

Views/SpacedRepetition/Start.cshtml
@model Noting.Models.NoteBox

@{
    ViewData["Title"] = "Start attempt";
}

<h1>Spaced Repetition</h1>
<h3 class="lead">Box @Model.Level.ToString().ToLower()</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Notes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var note in Model.Notes) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => note.Note.Title)
            </td>
            <td>
                @Html.ActionLink("Edit", "Notes", new { id = note.NoteId }) |
                @Html.ActionLink("Details", "Notes", new { id = note.NoteId }) |
                @Html.ActionLink("Delete", "Notes", new { id = note.NoteId })
            </td>
        </tr>
}
    </tbody>
</table>

<form asp-action="Attempt">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    @foreach (var note in Model.Notes)
    {
        <h4>@note.Note.Title</h4>
        <h5>@note.Note.SpacedRepetitionHistory.Question</h5>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input type="checkbox" class="form-check-input" for="Correct" /> Was your answer correct?
            </label>
        </div>
        <input type="hidden" for="SpacedRepetitionHistoryId" value="@note.Note.SpacedRepetitionHistory.Id" />
        <div class="form-group">
            <input type="submit" value="Create" class="btn btn-primary" />
        </div>
    }
</form>